apiVersion: apps/v1
kind: Deployment
metadata:
  name: netconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netconfig
  template:
    metadata:
      labels:
        app: netconfig                 
    spec:
      containers:
      - name: netconfig
        image: arambazamba/net-config
        env: 
          - name: App__UseSQLite
            value: 'false'
          - name: App__UseEnv
            value: 'true'
          - name: Azure__TenantId
            value: 'd9101020-90e0-4469-a129-6a32866c0d0a'
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "0.2"
            memory: "128Mi" 
      imagePullSecrets:
      - name: W+I0mZoRYW+mkeTvytZu2w2SOqjr=KoB       
---
apiVersion: v1
kind: Service
metadata:
  name: netconfig-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netconfig
---  