apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-shop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-shop-ui
  template:
    metadata:
      labels:
        app: food-shop-ui                 
    spec:
      containers:
      - name: foodui
        image: arambazamba/food-shop-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: food-shop-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: food-shop-ui
---
