apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-catalog-api
  template:
    metadata:
      labels:
        app: foodapi                 
    spec:
      containers:
      - name: foodapi
        image: arambazamba/food-catalog-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: food-catalog-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: food-catalog-api
---
